<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [3]:
bt_v = pd.read_csv("application_data/FT_variable.csv")

### state : H_D = 0, L_D = 1, L_U = 2, H_U = 3

In [4]:
bt_v

,Unnamed: 0,Application,variable,Perf_node01_power_energy_pkg_,a,Perf_node01_power_energy_ram_,b,Perf_node01_power_energy_total_,c
0,3779,FT,95,2,2,2,2,2,2
1,3780,FT,127,2,2,2,2,2,2
2,3781,FT,1,1,2,3,2,1,2
3,3782,FT,94,3,1,3,3,3,1
4,3783,FT,127,3,3,3,3,3,3
5,3784,FT,127,2,3,3,3,3,3
6,3785,FT,127,2,2,2,3,2,3
7,3786,FT,127,2,2,2,2,2,2
8,3787,FT,0,1,2,1,2,1,2
9,3788,FT,0,1,1,1,1,1,1
10,3789,FT,127,2,1,2,1,2,1
11,3790,FT,0,0,2,0,2,0,2
12,3791,FT,0,0,0,0,0,0,0
13,3792,FT,0,1,0,1,0,1,0
14,3793,FT,126,2,1,1,1,2,1
15,3794,FT,7,1,2,2,1,2,2
16,3795,FT,127,2,1,2,2,2,2
17,3796,FT,127,2,2,2,2,2,2
18,3797,FT,0,1,2,1,2,1,2
19,3798,FT,0,1,1,1,1,1,1
20,3799,FT,0,0,1,0,1,0,1
21,3800,FT,0,2,0,0,0,1,0
22,3801,FT,64,1,2,0,0,1,1
23,3802,FT,127,3,1,3,0,3,1
24,3803,FT,127,1,3,3,3,2,3
25,3804,FT,127,2,1,2,3,2,2
26,3805,FT,0,1,2,1,2,1,2
27,3806,FT,64,2,1,1,1,1,1
28,3807,FT,70,1,2,1,1,1,1
29,3808,FT,3,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
1570,5349,FT,4,1,1,2,3,1,1
1571,5350,FT,0,2,1,1,2,1,1
1572,5351,FT,126,1,2,2,1,2,1
1573,5352,FT,97,2,1,1,2,2,2
1574,5353,FT,96,1,2,2,1,1,2
1575,5354,FT,127,2,1,1,2,2,1
1576,5355,FT,64,1,2,1,1,1,2
1577,5356,FT,0,0,1,1,1,0,1
1578,5357,FT,0,0,0,0,1,0,0
1579,5358,FT,127,3,0,3,0,3,0
1580,5359,FT,1,1,3,2,3,1,3
1581,5360,FT,100,2,1,1,2,2,1
1582,5361,FT,63,1,2,2,1,1,2
1583,5362,FT,64,2,1,1,2,2,1
1584,5363,FT,68,1,2,2,1,1,2
1585,5364,FT,127,2,1,1,2,2,1
1586,5365,FT,10,1,2,1,1,1,2
1587,5366,FT,127,2,1,2,1,2,1
1588,5367,FT,7,1,2,1,2,1,2
1589,5368,FT,63,2,1,2,1,2,1
1590,5369,FT,116,2,2,1,2,2,2
1591,5370,FT,7,1,2,2,1,1,2
1592,5371,FT,0,1,1,2,2,2,1
1593,5372,FT,127,2,1,2,2,2,2
1594,5373,FT,126,2,2,1,2,2,2
1595,5374,FT,123,2,2,1,1,2,2
1596,5375,FT,0,1,2,1,1,1,2
1597,5376,FT,0,0,1,0,1,0,1
1598,5377,FT,1,0,0,0,0,0,0
1599,5378,FT,64,2,0,1,0,2,0

# pkg, ram, total power matrix

In [5]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [6]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [7]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [8]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [9]:
pkg_matrix

array([[0.192, 0.263, 0.131, 0.414],
       [0.079, 0.331, 0.546, 0.044],
       [0.028, 0.633, 0.325, 0.013],
       [0.023, 0.593, 0.349, 0.035]])

## 2. ram_matrix

In [10]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [11]:
ram_matrix

array([[0.256, 0.088, 0.08 , 0.576],
       [0.104, 0.351, 0.525, 0.02 ],
       [0.029, 0.645, 0.309, 0.017],
       [0.014, 0.255, 0.4  , 0.331]])

## 3. total_matrix

In [12]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [13]:
total_matrix

array([[0.248, 0.147, 0.138, 0.468],
       [0.086, 0.334, 0.551, 0.029],
       [0.027, 0.642, 0.316, 0.015],
       [0.011, 0.425, 0.506, 0.057]])

# Variable count

In [14]:
np.set_printoptions(threshold=sys.maxsize)

In [15]:
q = bt_v['variable'].unique()
le = q.size
print(np.sort(q),"\n",q.size)

[  0   1   2   3   4   5   6   7   9  10  11  13  15  24  25  27  29  30
  31  32  33  34  35  36  37  38  39  41  46  47  48  50  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  79  88  90  92  93  94
  95  96  97  98  99 100 101 102 103 108 109 111 112 114 116 118 119 120
 121 122 123 124 125 126 127]
 79

In [16]:
pkg_var_matrix = np.zeros((4,le))
ram_var_matrix = np.zeros((4,le))
total_var_matrix = np.zeros((4,le))

## 1. pkg + variable

In [17]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [18]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [19]:
pkg_var_matrix

array([[ 97.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.],
       [272., 109.,   8.,  27.,  16.,  12.,   7.,  27.,   3.,   1.,   2.,
          2.,   6.,   5.,  13.,   3.,   3.,   2.,  30.,   8.,   1.,   2.,
          1.,   0.,   1.,   3.,   2.,   1.,   2.,   0.,   0.,   0.,   1.,
          1.,   0.,   0.,   1.,   2.,   4.,   4.,  48.,  11.,   3.,   6.,
         12.,   6.,   6.,  12.,   5.,   2.,   2.,   1.,   1.,   3.,   7.,
          9.,   0.,   1.,   1.,   0.,   0.,   1.,   1.,   1.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   2.,   1.,   1.,   2.,   1.,   0.,
          3.,  16.],
       [ 15.,   3.,   0.,   0.,   3.,   0.,   0.,   1.,   1.,   0.,   0.,
          1.,   2.,   0.,   2.,   1.,   0.,   1.,   3.,  11.,   2.,   3.,
          0.,   2.,   0.,   3.,   1.,   0.,   2.,   1.,   2.,   1.,   3.,
          3.,   2.,   2.,   1.,   1.,  10.,  40.,  15.,   0.,   0.,   0.,
          1.,   0.,   1.,   1.,   1.,   0.,   0.,   1.,   0.,   5.,   1.,
         32.,   1.,   1.,   1.,   5.,   2.,   6.,   7.,   0.,   1.,   3.,
          3.,   2.,   5.,   2.,   3.,  11.,   3.,   9.,  16.,  21.,   7.,
         93., 285.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,
          0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          6.,  77.]])

In [20]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [21]:
pkg_var_matrix

array([[0.98 , 0.02 , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.364, 0.146, 0.011, 0.036, 0.021, 0.016, 0.009, 0.036, 0.004,
        0.001, 0.003, 0.003, 0.008, 0.007, 0.017, 0.004, 0.004, 0.003,
        0.04 , 0.011, 0.001, 0.003, 0.001, 0.   , 0.001, 0.004, 0.003,
        0.001, 0.003, 0.   , 0.   , 0.   , 0.001, 0.001, 0.   , 0.   ,
        0.001, 0.003, 0.005, 0.005, 0.064, 0.015, 0.004, 0.008, 0.016,
        0.008, 0.008, 0.016, 0.007, 0.003, 0.003, 0.001, 0.001, 0.004,
        0.009, 0.012, 0.   , 0.001, 0.001, 0.   , 0.   , 0.001, 0.001,
        0.001, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.003,
        0.001, 0.001, 0.003, 0.001, 0.   , 0.004, 0.021],
       [0.022, 0.004, 0.   , 0.   , 0.004, 0.   , 0.   , 0.001, 0.001,
        0.   , 0.   , 0.001, 0.003, 0.   , 0.003, 0.001, 0.   , 0.001,
        0.004, 0.016, 0.003, 0.004, 0.   , 0.003, 0.   , 0.004, 0.001,
        0.   , 0.003, 0.001, 0.003, 0.001, 0.004, 0.004, 0.003, 0.003,
        0.001, 0.001, 0.015, 0.06 , 0.022, 0.   , 0.   , 0.   , 0.001,
        0.   , 0.001, 0.001, 0.001, 0.   , 0.   , 0.001, 0.   , 0.007,
        0.001, 0.048, 0.001, 0.001, 0.001, 0.007, 0.003, 0.009, 0.01 ,
        0.   , 0.001, 0.004, 0.004, 0.003, 0.007, 0.003, 0.004, 0.016,
        0.004, 0.013, 0.024, 0.031, 0.01 , 0.139, 0.427],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.012, 0.   , 0.   , 0.   ,
        0.   , 0.012, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.012,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.07 , 0.895]])

## 2. ram + variable

In [22]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [23]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [24]:
ram_var_matrix

array([[102.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   5.,   0.,   0.,   0.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   2.,   0.,
          1.,   0.,   0.,   0.,   1.,   0.,   2.,   2.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   1.,   0.,
          2.,   4.],
       [244.,  84.,   6.,  21.,  10.,   9.,   5.,  19.,   1.,   1.,   0.,
          2.,   7.,   1.,   3.,   0.,   1.,   3.,  14.,   6.,   1.,   1.,
          1.,   1.,   1.,   3.,   1.,   1.,   0.,   1.,   1.,   0.,   1.,
          2.,   1.,   1.,   2.,   1.,   6.,  10.,  37.,  10.,   2.,   4.,
          6.,   5.,   4.,   8.,   2.,   1.,   2.,   1.,   1.,   4.,   5.,
         18.,   1.,   0.,   2.,   2.,   1.,   3.,   5.,   1.,   0.,   1.,
          1.,   2.,   2.,   1.,   1.,   4.,   2.,   3.,  10.,   3.,   3.,
         24.,  45.],
       [ 36.,  18.,   2.,   5.,   9.,   3.,   2.,   9.,   1.,   0.,   0.,
          0.,   1.,   3.,   6.,   1.,   0.,   0.,   8.,  12.,   2.,   4.,
          0.,   1.,   0.,   3.,   2.,   0.,   4.,   0.,   1.,   1.,   3.,
          1.,   1.,   1.,   0.,   2.,   8.,  27.,  21.,   1.,   1.,   2.,
          7.,   1.,   2.,   5.,   4.,   1.,   0.,   1.,   0.,   1.,   3.,
         21.,   0.,   2.,   0.,   2.,   1.,   2.,   1.,   0.,   1.,   2.,
          2.,   0.,   3.,   1.,   1.,   8.,   2.,   7.,   8.,  17.,   4.,
         73., 245.],
       [  2.,  11.,   0.,   1.,   0.,   0.,   0.,   0.,   2.,   0.,   2.,
          1.,   0.,   1.,   6.,   3.,   2.,   0.,  11.,   1.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,
          1.,   0.,   0.,   0.,   1.,   0.,   7.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   2.,   0.,
          1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   1.,   0.,
          3.,  84.]])

In [25]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [26]:
ram_var_matrix

array([[0.816, 0.008, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.04 , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.008, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.016,
        0.   , 0.008, 0.   , 0.   , 0.   , 0.008, 0.   , 0.016, 0.016,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.008, 0.   ,
        0.   , 0.   , 0.   , 0.008, 0.   , 0.016, 0.032],
       [0.349, 0.12 , 0.009, 0.03 , 0.014, 0.013, 0.007, 0.027, 0.001,
        0.001, 0.   , 0.003, 0.01 , 0.001, 0.004, 0.   , 0.001, 0.004,
        0.02 , 0.009, 0.001, 0.001, 0.001, 0.001, 0.001, 0.004, 0.001,
        0.001, 0.   , 0.001, 0.001, 0.   , 0.001, 0.003, 0.001, 0.001,
        0.003, 0.001, 0.009, 0.014, 0.053, 0.014, 0.003, 0.006, 0.009,
        0.007, 0.006, 0.011, 0.003, 0.001, 0.003, 0.001, 0.001, 0.006,
        0.007, 0.026, 0.001, 0.   , 0.003, 0.003, 0.001, 0.004, 0.007,
        0.001, 0.   , 0.001, 0.001, 0.003, 0.003, 0.001, 0.001, 0.006,
        0.003, 0.004, 0.014, 0.004, 0.004, 0.034, 0.064],
       [0.057, 0.029, 0.003, 0.008, 0.014, 0.005, 0.003, 0.014, 0.002,
        0.   , 0.   , 0.   , 0.002, 0.005, 0.01 , 0.002, 0.   , 0.   ,
        0.013, 0.019, 0.003, 0.006, 0.   , 0.002, 0.   , 0.005, 0.003,
        0.   , 0.006, 0.   , 0.002, 0.002, 0.005, 0.002, 0.002, 0.002,
        0.   , 0.003, 0.013, 0.043, 0.033, 0.002, 0.002, 0.003, 0.011,
        0.002, 0.003, 0.008, 0.006, 0.002, 0.   , 0.002, 0.   , 0.002,
        0.005, 0.033, 0.   , 0.003, 0.   , 0.003, 0.002, 0.003, 0.002,
        0.   , 0.002, 0.003, 0.003, 0.   , 0.005, 0.002, 0.002, 0.013,
        0.003, 0.011, 0.013, 0.027, 0.006, 0.116, 0.389],
       [0.014, 0.076, 0.   , 0.007, 0.   , 0.   , 0.   , 0.   , 0.014,
        0.   , 0.014, 0.007, 0.   , 0.007, 0.041, 0.021, 0.014, 0.   ,
        0.076, 0.007, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.007, 0.007, 0.   , 0.   ,
        0.   , 0.007, 0.   , 0.048, 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.014,
        0.   , 0.007, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.007,
        0.   , 0.   , 0.   , 0.007, 0.   , 0.021, 0.579]])

## 3. total + variable

In [27]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_total_'], bt_v['variable'])

In [28]:
for i in range(len(total_var_matrix)):
    total_var_matrix[i] = tem_matrix[i]

In [29]:
total_var_matrix

array([[105.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.],
       [265., 105.,   8.,  27.,  15.,  12.,   6.,  25.,   2.,   1.,   0.,
          2.,   6.,   5.,  13.,   3.,   3.,   3.,  25.,   8.,   1.,   1.,
          1.,   1.,   1.,   3.,   1.,   1.,   2.,   0.,   1.,   0.,   1.,
          2.,   1.,   0.,   2.,   2.,   4.,   4.,  52.,  11.,   2.,   5.,
         11.,   6.,   4.,  12.,   5.,   1.,   2.,   2.,   1.,   5.,   6.,
         11.,   0.,   1.,   1.,   0.,   1.,   2.,   0.,   1.,   0.,   0.,
          0.,   1.,   0.,   1.,   0.,   2.,   2.,   0.,   3.,   0.,   0.,
          3.,  13.],
       [ 14.,   8.,   0.,   0.,   4.,   0.,   1.,   3.,   2.,   0.,   2.,
          1.,   2.,   0.,   2.,   1.,   0.,   0.,   8.,  11.,   2.,   4.,
          0.,   1.,   0.,   3.,   2.,   0.,   2.,   1.,   1.,   1.,   3.,
          1.,   1.,   2.,   0.,   1.,  10.,  40.,  10.,   0.,   1.,   1.,
          2.,   0.,   2.,   1.,   1.,   1.,   0.,   0.,   0.,   3.,   2.,
         30.,   1.,   1.,   1.,   5.,   1.,   5.,   7.,   0.,   1.,   3.,
          3.,   1.,   5.,   1.,   3.,  11.,   2.,  10.,  15.,  22.,   7.,
         94., 287.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,
          1.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          5.,  78.]])

In [30]:
sum = 0

for i in range(len(total_var_matrix)):
    for j in range(len(total_var_matrix[0])):
        sum = sum + total_var_matrix[i][j]
    for k in range(len(total_var_matrix[0])):
        po = total_var_matrix[i][k] / sum
        total_var_matrix[i][k] = po.round(3)
    sum = 0

In [31]:
total_var_matrix

array([[0.963, 0.009, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.009, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.009, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.009,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.363, 0.144, 0.011, 0.037, 0.021, 0.016, 0.008, 0.034, 0.003,
        0.001, 0.   , 0.003, 0.008, 0.007, 0.018, 0.004, 0.004, 0.004,
        0.034, 0.011, 0.001, 0.001, 0.001, 0.001, 0.001, 0.004, 0.001,
        0.001, 0.003, 0.   , 0.001, 0.   , 0.001, 0.003, 0.001, 0.   ,
        0.003, 0.003, 0.005, 0.005, 0.071, 0.015, 0.003, 0.007, 0.015,
        0.008, 0.005, 0.016, 0.007, 0.001, 0.003, 0.003, 0.001, 0.007,
        0.008, 0.015, 0.   , 0.001, 0.001, 0.   , 0.001, 0.003, 0.   ,
        0.001, 0.   , 0.   , 0.   , 0.001, 0.   , 0.001, 0.   , 0.003,
        0.003, 0.   , 0.004, 0.   , 0.   , 0.004, 0.018],
       [0.021, 0.012, 0.   , 0.   , 0.006, 0.   , 0.001, 0.004, 0.003,
        0.   , 0.003, 0.001, 0.003, 0.   , 0.003, 0.001, 0.   , 0.   ,
        0.012, 0.016, 0.003, 0.006, 0.   , 0.001, 0.   , 0.004, 0.003,
        0.   , 0.003, 0.001, 0.001, 0.001, 0.004, 0.001, 0.001, 0.003,
        0.   , 0.001, 0.015, 0.059, 0.015, 0.   , 0.001, 0.001, 0.003,
        0.   , 0.003, 0.001, 0.001, 0.001, 0.   , 0.   , 0.   , 0.004,
        0.003, 0.045, 0.001, 0.001, 0.001, 0.007, 0.001, 0.007, 0.01 ,
        0.   , 0.001, 0.004, 0.004, 0.001, 0.007, 0.001, 0.004, 0.016,
        0.003, 0.015, 0.022, 0.033, 0.01 , 0.139, 0.426],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.011, 0.011, 0.   , 0.   ,
        0.   , 0.011, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.011,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.057, 0.897]])