<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [64]:
bt_v = pd.read_csv("application_data/IS_variable.csv")

### state : H_D = 0, L_D = 1, L_U = 2, H_U = 3

In [65]:
bt_v

,Unnamed: 0,Application,variable,Perf_node01_power_energy_pkg_,a,Perf_node01_power_energy_ram_,b,Perf_node01_power_energy_total_,c
0,5379,IS,94,2,2,2,2,2,2
1,5380,IS,127,2,2,1,2,2,2
2,5381,IS,127,2,2,1,1,2,2
3,5382,IS,127,2,2,3,1,2,2
4,5383,IS,94,2,2,1,3,2,2
5,5384,IS,0,2,2,3,1,2,2
6,5385,IS,127,3,2,3,3,3,2
7,5386,IS,127,1,3,3,3,2,3
8,5387,IS,0,0,1,1,3,0,2
9,5388,IS,126,3,0,1,1,2,0
10,5389,IS,1,1,3,2,1,1,2
11,5390,IS,118,3,1,1,2,2,1
12,5391,IS,25,1,3,2,1,1,2
13,5392,IS,102,2,1,1,2,2,1
14,5393,IS,24,1,2,2,1,1,2
15,5394,IS,96,2,1,2,2,2,1
16,5395,IS,95,1,2,2,2,1,2
17,5396,IS,103,2,1,1,2,2,1
18,5397,IS,31,1,2,3,1,1,2
19,5398,IS,0,2,1,0,3,1,1
20,5399,IS,127,1,2,3,0,2,1
21,5400,IS,1,2,1,0,3,1,2
22,5401,IS,60,1,2,2,0,1,1
23,5402,IS,70,2,1,0,2,2,1
24,5403,IS,27,1,2,2,0,1,2
25,5404,IS,103,2,1,2,2,2,1
26,5405,IS,25,1,2,2,2,1,2
27,5406,IS,32,2,1,1,2,2,1
28,5407,IS,30,1,2,1,1,1,2
29,5408,IS,100,2,1,1,1,2,1
...,...,...,...,...,...,...,...,...,...
40,5419,IS,102,2,3,1,0,1,3
41,5420,IS,127,3,2,3,1,3,1
42,5421,IS,127,2,3,3,3,2,3
43,5422,IS,0,0,2,0,3,0,2
44,5423,IS,126,3,0,3,0,3,0
45,5424,IS,0,0,3,0,3,0,3
46,5425,IS,126,3,0,2,0,3,0
47,5426,IS,1,0,3,1,2,0,3
48,5427,IS,126,3,0,2,1,3,0
49,5428,IS,0,0,3,1,2,0,3
50,5429,IS,126,2,0,2,1,2,0
51,5430,IS,1,1,2,1,2,1,2
52,5431,IS,118,2,1,2,1,2,1
53,5432,IS,29,1,2,2,2,1,2
54,5433,IS,102,2,1,1,2,2,1
55,5434,IS,25,1,2,2,1,1,2
56,5435,IS,96,2,1,0,2,2,1
57,5436,IS,95,1,2,3,0,1,2
58,5437,IS,102,2,1,1,3,2,1
59,5438,IS,89,1,2,2,1,1,2
60,5439,IS,98,2,1,0,2,2,1
61,5440,IS,94,1,2,3,0,1,2
62,5441,IS,32,2,1,1,3,2,1
63,5442,IS,94,1,2,2,1,1,2
64,5443,IS,0,2,1,1,2,1,1
65,5444,IS,24,2,2,1,1,1,1
66,5445,IS,0,1,2,2,1,1,1
67,5446,IS,0,1,1,1,2,1,1
68,5447,IS,33,0,1,0,1,0,1
69,5448,IS,0,2,0,0,0,1,0

# pkg, ram, total power matrix

In [66]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [67]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [68]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [69]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [70]:
pkg_matrix

array([[0.   , 0.125, 0.25 , 0.625],
       [0.13 , 0.043, 0.783, 0.043],
       [0.065, 0.581, 0.29 , 0.065],
       [0.375, 0.375, 0.25 , 0.   ]])

## 2. ram_matrix

In [71]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [72]:
ram_matrix

array([[0.167, 0.167, 0.25 , 0.417],
       [0.083, 0.25 , 0.458, 0.208],
       [0.143, 0.571, 0.286, 0.   ],
       [0.462, 0.308, 0.   , 0.231]])

## 3. total_matrix

In [73]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [74]:
total_matrix

array([[0.   , 0.25 , 0.25 , 0.5  ],
       [0.077, 0.231, 0.654, 0.038],
       [0.1  , 0.6  , 0.267, 0.033],
       [0.5  , 0.167, 0.333, 0.   ]])

# Variable count

In [75]:
np.set_printoptions(threshold=sys.maxsize)

In [76]:
q = bt_v['variable'].unique()
le = q.size
print(np.sort(q),"\n",q.size)

[  0   1  24  25  27  29  30  31  32  33  36  60  70  89  94  95  96  98
 100 102 103 118 126 127]
 24

In [77]:
pkg_var_matrix = np.zeros((4,26))
ram_var_matrix = np.zeros((4,26))
total_var_matrix = np.zeros((4,26))

## 1. pkg + variable

In [78]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [79]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [80]:
pkg_var_matrix

array([[4., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [4., 2., 0., 0., 2., 3., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
        2., 2., 0., 0., 0., 0., 0., 0., 0., 2.],
       [4., 1., 0., 0., 1., 0., 0., 0., 0., 0., 2., 0., 1., 0., 1., 0.,
        3., 1., 2., 1., 1., 4., 2., 1., 1., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 4., 2.]])

In [81]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [82]:
pkg_var_matrix

array([[0.5  , 0.125, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.375, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.174, 0.087, 0.   , 0.   , 0.087, 0.13 , 0.043, 0.043, 0.043,
        0.043, 0.   , 0.   , 0.   , 0.043, 0.   , 0.043, 0.087, 0.087,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.087],
       [0.129, 0.032, 0.   , 0.   , 0.032, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.065, 0.   , 0.032, 0.   , 0.032, 0.   , 0.097, 0.032,
        0.065, 0.032, 0.032, 0.129, 0.065, 0.032, 0.032, 0.161],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.125, 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.125, 0.5  , 0.25 ]])

## 2. ram + variable

In [83]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [84]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [85]:
ram_var_matrix

array([[5., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 1., 0.,
        1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [5., 2., 0., 0., 2., 0., 0., 0., 1., 0., 2., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 4., 1., 1., 1., 3.],
       [1., 1., 0., 0., 1., 3., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
        2., 1., 1., 0., 0., 0., 1., 1., 3., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        2., 1., 0., 0., 0., 0., 0., 0., 1., 6.]])

In [86]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [87]:
ram_var_matrix

array([[0.385, 0.077, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.154, 0.   , 0.   , 0.077, 0.   , 0.077, 0.077,
        0.077, 0.077, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.208, 0.083, 0.   , 0.   , 0.083, 0.   , 0.   , 0.   , 0.042,
        0.   , 0.083, 0.   , 0.   , 0.   , 0.   , 0.   , 0.042, 0.   ,
        0.   , 0.   , 0.042, 0.167, 0.042, 0.042, 0.042, 0.125],
       [0.05 , 0.05 , 0.   , 0.   , 0.05 , 0.15 , 0.05 , 0.05 , 0.   ,
        0.   , 0.   , 0.   , 0.05 , 0.05 , 0.   , 0.05 , 0.1  , 0.05 ,
        0.05 , 0.   , 0.   , 0.   , 0.05 , 0.05 , 0.15 , 0.   ],
       [0.077, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.077, 0.   , 0.077, 0.   , 0.   , 0.   , 0.   , 0.154, 0.077,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.077, 0.462]])

## 3. total + variable

In [88]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_total_'], bt_v['variable'])

In [89]:
for i in range(len(total_var_matrix)):
    total_var_matrix[i] = tem_matrix[i]

In [90]:
total_var_matrix

array([[4., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [7., 3., 0., 0., 3., 3., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
        2., 2., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 1., 0., 1., 0.,
        3., 1., 2., 1., 1., 3., 2., 2., 2., 7.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 3., 2.]])

In [91]:
sum = 0

for i in range(len(total_var_matrix)):
    for j in range(len(total_var_matrix[0])):
        sum = sum + total_var_matrix[i][j]
    for k in range(len(total_var_matrix[0])):
        po = total_var_matrix[i][k] / sum
        total_var_matrix[i][k] = po.round(3)
    sum = 0

In [92]:
total_var_matrix

array([[0.5  , 0.125, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.375, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.259, 0.111, 0.   , 0.   , 0.111, 0.111, 0.037, 0.037, 0.037,
        0.037, 0.   , 0.   , 0.   , 0.037, 0.   , 0.037, 0.074, 0.074,
        0.   , 0.   , 0.   , 0.037, 0.   , 0.   , 0.   , 0.   ],
       [0.034, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.069, 0.   , 0.034, 0.   , 0.034, 0.   , 0.103, 0.034,
        0.069, 0.034, 0.034, 0.103, 0.069, 0.069, 0.069, 0.241],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.167, 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.5  , 0.333]])